name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    run: cd ./.github/workflows
    run: docker build ./.github/workflows/ --file Dockerfile --tag hak5c2-docker:$(date +%s)
